name: ravis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.1.1
  table_calendar: ^3.0.6
  intl: ^0.17.0
  url_launcher: ^6.0.10
  http: ^0.13.3
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/



flutter_native_splash:
  color: "#ffffff"
  image: assets\splash2.png

  android_12:
    color: "#ffffff"
    image: assets\splash2.png
